### ISSUE TITLE
missing pillow from requirements

### ISSUE THREAD

**Issue by davelin1** [GaelVaroquaux/stats_in_python_tutorial#1]
thanks for publishing this. 
was getting the following error (see below) when trying to make html
solved by pip installing pillow

(ipython)$  make html
mkdir -p _build/html _build/doctrees
sphinx-build -b html -d _build/doctrees -D latex_paper_size=a4  . _build/html
Running Sphinx v1.3.1

Extension error:
Could not import extension gen_rst (exception: No module named Image)
make: **\* [html] Error 1

**Comment by GaelVaroquaux** [comment]
Indeed, pillow is needed. I should point out that this tutorial should
not be used anymore, as it has been integrated in the scipy-lectures
(http://scipy-lectures.org). They are harder to build :$, but much more
comprehensive and kept up to date.
