### ISSUE TITLE
small warning issue coming with recent pandas(?) release

### ISSUE THREAD

**Issue by stonebig** [GaelVaroquaux/stats_in_python_tutorial#2]
you must now write 

```
groupby_gender.boxplot(column=['FSIQ', 'VIQ', 'PIQ'], return_type='axes')
```

not to get a (very kind but) warning

**Comment by GaelVaroquaux** [comment]
Thanks. I think that this warning is harmless and we'll have to live with
it for now.

Speaking of deprecations, this tutorial is deprecated, and the maintained
version is in the scipy lectures:
http://www.scipy-lectures.org/packages/statistics/index.html

The reason why I cannot change the call to boxplot, is that the
scipy-lectures are tested and garantied to work with a version of pandas
that is not the bleeding edge.

Thanks for the report, though!
